# Generated by Django 4.0.5 on 2022-06-26 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_list',
            old_name='BookTitle',
            new_name='Db_Name',
        ),
        migrations.CreateModel(
            name='Book_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.CharField(max_length=500)),
                ('cart_boolean', models.BooleanField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book_list')),
            ],
        ),
    ]
