# Generated by Django 4.0.5 on 2022-07-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_item',
            name='content',
            field=models.CharField(default='Shut up!', max_length=500),
        ),
    ]
