# Generated by Django 4.0.5 on 2022-07-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_book_item_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_item',
            name='image',
            field=models.CharField(default='nikal bc!', max_length=500),
        ),
        migrations.AddField(
            model_name='book_item',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
